### ISSUE TITLE
Call for help! -> Frontend content not visible (but admin backend)

### ISSUE THREAD

**Issue by nextgen-networks** [nextgen-networks/rainloop-nextcloud#4]
Rainloop can be activated within NC14.
Frontend content does not show up if menu icon gets clicked :-(

Backend Link is visible in admin section - content is displayed and could be configured.

**Comment by tabp0le** [comment]
So, rainloop itself is working. I think something with the iframe is messed up. I can access rainloop directly if i go to https://nextcloudurl/apps/rainloop/app

**Comment by nextgen-networks** [comment]
... hmm - did not work for me.
Gray background is loaded, even the favicon - but nothing else.

**Comment by tabp0le** [comment]
Oh my god. Add a trailing slash to the end. :P

**Comment by tabp0le** [comment]
I think the issue is a simple regex problem lmao

**Comment by nextgen-networks** [comment]
... may this caused by the "old" routes.php in appinfo?

**Comment by tabp0le** [comment]
OK, the issue is pure styling. I'm getting much closer :+1: 

See templates/index.php for the area in which the problem resides.

![rainloop](https://user-images.githubusercontent.com/6798003/45516771-0f3a7480-b761-11e8-88aa-f1ec9150c521.png)

**Comment by tabp0le** [comment]
GOT IT!
![image](https://user-images.githubusercontent.com/6798003/45517029-c800b380-b761-11e8-89bf-896edba6f726.png)

**Comment by nextgen-networks** [comment]
Wow! @tabp0le you're fantastic!

**Comment by tabp0le** [comment]
Thanks! Hey, you started the process. I just figured i'd help out if I could. I sure want my rainloop too! :)

**Comment by nextgen-networks** [comment]
... seems to work very smooth :-)
One interesting thing: rainloop 1.21.1 has no OpenPGP plungin (or is it only invisible?)

**Comment by tabp0le** [comment]
Damn, you're right. We may need to update it or something.

**Comment by tabp0le** [comment]
Update: Actually the plugin is working fine. I think it deleted my old keys, but I was able to generate new one.

**Comment by nextgen-networks** [comment]
Creepy - decrypting an message works well.
... but menu entry is missing:
![rainloopnc14](https://user-images.githubusercontent.com/21206978/45520459-c9f66100-b7b9-11e8-9c1c-f977b4d4f538.jpg)

**Comment by tabp0le** [comment]
I'd double check in admin settings. Make sure it's enabled. Who knows, it inadvertently gotten disabled.

![screenshot_20180913_160831](https://user-images.githubusercontent.com/6798003/45520669-4b74d180-b76f-11e8-91ea-a7d63db1c087.png)

**Comment by nextgen-networks** [comment]
... shit - missed that setting.
Thanks eagle eye! :-)

**Comment by gymnae** [comment]
Thank you @tabp0le for your efforts and time and @nextgen-networks for getting the ball rolling!
